### ISSUE TITLE
Set navigation bar transparent

### ISSUE THREAD

**Issue by kaisiamza51** [cillyfly/MXScroll#2]
How to set navigation bar transparent when viewDidload 

and set navigation bar to white color when scroll up like this

https://www.youtube.com/watch?v=DiV8wO9iLds

Thank you

**Comment by cillyfly** [comment]
If you want to do something in `viewdidload` you can use code blow
```       
 Observable.just(Void()).asObservable().debug("AA").subscribe { (eve) in
            if !eve.isStopEvent{
                print("1 DO SOMETHING IN VIEWDIDLOAD")
            }
        }.disposed(by: dispose)
```
 
The effect of navigation bar is not currently implemented.

**Comment by cillyfly** [comment]
some advise 
maybe you can use this [AMScrollingNavbar](https://github.com/andreamazz/AMScrollingNavbar)
