### ISSUE TITLE
SegmentView with both icons and title and the selected option should be highlighted

### ISSUE THREAD

**Issue by Panduranga-iOS** [cillyfly/MXScroll#3]
I have integrated your library in to our project for the purpose of sticky header, we have achieved the same and glad to use your library, we have to show the title and icons in the segmented view, but the icons are half visible, I tried to enhance the segment view's height, but in vain, I request you to prepare an example for implementing the segmented view with both icons and title, provided the selected option should be highlighted.

or else, Kindly send an example how to use a custom segmented control.

Thanks & Regards
![simulator screen shot - iphone xr - 2018-12-31 at 20 30 24](https://user-images.githubusercontent.com/46198678/50562580-02a35180-0d3b-11e9-8cfd-a06adfb19325.png)

**Comment by cillyfly** [comment]
Add images just use this code 
```
        let segment = MSSegmentControl(sectionTitles: ["Comment","Sport"], sectionImages: [#imageLiteral(resourceName: "O"),#imageLiteral(resourceName: "r")], selectedImages:[ #imageLiteral(resourceName: "O_selected"),#imageLiteral(resourceName: "r_selected")])
```
Change segment height use this 
```
      mx.segmentViewHeight = 100
```
![image](https://user-images.githubusercontent.com/6388202/50627233-7e84e000-0f6d-11e9-9ba5-4a20a0ab196d.png)

The result 
![image](https://user-images.githubusercontent.com/6388202/50627247-8e9cbf80-0f6d-11e9-9e46-d07bfd3f30cc.png)

If you want to use the custom Segment. you should implement MXSegmentProtocol  as the readme show  and it will be ok

**Comment by cillyfly** [comment]
close
