### ISSUE TITLE
Segment view related issue

### ISSUE THREAD

**Issue by YashBhikadiya** [cillyfly/MXScroll#6]
When I have used 2 segments at that time its works very good, but if when I have used 1 segment that time it's not working properly. Segment title was not shown when we only 1 segment added. For more understanding picture is attached below.

Segment shown Image:

![Simulator Screen Shot - iPhone 8 - 2020-01-11 at 16 04 16](https://user-images.githubusercontent.com/59763382/72203068-f3e29500-348c-11ea-8b73-0250dfcb4536.png)

Coding Image:
![Screenshot 2020-01-11 at 4 04 44 PM](https://user-images.githubusercontent.com/59763382/72203080-0a88ec00-348d-11ea-9dbc-17f31638ae16.png)

Please give me a solution as soon as possible.

**Comment by cillyfly** [comment]
I have checkout lastest master code . it seems no problem 

<img width="417" alt="image" src="https://user-images.githubusercontent.com/6388202/77177770-07e7ea00-6b01-11ea-84c6-0b0427158ff7.png">

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/6388202/77177794-1504d900-6b01-11ea-8df5-be90bd6da92e.png">
