### ISSUE TITLE
addSubView in MXViewController make contentScrollView Offset down 44

### ISSUE THREAD

**Issue by swelzh** [cillyfly/MXScroll#8]
when I  addSubView in MXViewController  in viewDidLoad ,
the make contentScrollView Offset down 44
My Code is:

var navView = BaseNavView(frame: CGRect(x: 0, y: 0, width: KScreenWidth, height: kNavH))

public override func viewDidLoad() {
        super.viewDidLoad()
         view.addSubview(navView)
}

**Comment by cillyfly** [comment]
you should not use mxviewcontroller directly and add constant for navView 

```
Class youViewController:MXViewController{
public override func viewDidLoad() {
super.viewDidLoad()
view.addSubview(navView)

navView.easy.layout(
  Top(10),  
  Left(10),
  Right(10)}
)
}
}
```

xxxx 

and add a scrollview or webview or tableview in youVIiewController

may it will help you

**Comment by swelzh** [comment]
OK !   Thanks for you resolution!!


cillyfly <notifications@github.com> 于2020年3月20日周五 下午10:58写道：
